[toolchain]
anchor_version = "0.30.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
sweepr = "6bvmJVnmogfwcVTrU9y6MaM9G8vYRQBXeHbiZw5BU2sC"

[programs.devnet]
sweepr = "6bvmJVnmogfwcVTrU9y6MaM9G8vYRQBXeHbiZw5BU2sC"

[programs.mainnet]
sweepr = "6bvmJVnmogfwcVTrU9y6MaM9G8vYRQBXeHbiZw5BU2sC"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p tsconfig.json tests/**/*.ts --timeout 60000"
